"""
Backend Agent - Specialized in API, database, and business logic generation
"""

from typing import Dict, Optional
from datetime import datetime


class BackendAgent:
    """
    Specialized agent for backend development tasks.
    Generates API endpoints, database models, and business logic.
    """

    def __init__(self, orchestrator=None):
        """
        Initialize Backend Agent.
        
        Args:
            orchestrator: Reference to TaskOrchestrator
        """
        self.orchestrator = orchestrator
        self.name = "Backend Agent"
        self.role = "Backend Developer"
        self.specialties = ["API design", "Database modeling", "Business logic"]

    def generate_code(self, subtask: Dict) -> Dict:
        """
        Generate backend code from a subtask.
        
        Args:
            subtask: Backend subtask from decomposer
                {
                    "type": "backend",
                    "description": "...",
                    "task_id": "...",
                    ...
                }
        
        Returns:
            Dictionary with generated code and metadata
        """
        subtask_desc = subtask.get("description", "")
        task_id = subtask.get("task_id", "")
        
        # Generate backend code structure
        code = self._generate_api_structure(subtask_desc)
        code += "\n\n"
        code += self._generate_database_models(subtask_desc)
        code += "\n\n"
        code += self._generate_business_logic(subtask_desc)
        code += "\n\n"
        code += self._generate_error_handling()
        
        return {
            "code": code,
            "language": "python",
            "agent": self.name,
            "subtask_id": task_id,
            "generated_at": datetime.now().isoformat(),
            "documentation": self._generate_documentation(subtask_desc),
            "dependencies": self._identify_dependencies(subtask_desc),
        }

    def _generate_api_structure(self, description: str) -> str:
        """Generate API endpoint structure"""
        code = '''"""
Backend API Module - Auto-generated by Backend Agent
"""

from typing import Dict, List, Optional
from datetime import datetime
import json
from enum import Enum


class APIResponse:
    """Standard API response wrapper"""
    def __init__(self, status: str, data: Dict = None, error: str = None):
        self.status = status  # "success" or "error"
        self.data = data or {}
        self.error = error
        self.timestamp = datetime.now().isoformat()
    
    def to_dict(self) -> Dict:
        """Convert response to dictionary"""
        return {
            "status": self.status,
            "data": self.data,
            "error": self.error,
            "timestamp": self.timestamp,
        }


class APIEndpoint:
    """Base class for API endpoints"""
    def __init__(self, path: str, method: str = "GET"):
        self.path = path
        self.method = method
        self.handlers = {}
    
    def register_handler(self, handler_func):
        """Register handler for this endpoint"""
        self.handlers[self.method] = handler_func
        return handler_func
    
    async def handle_request(self, data: Dict = None) -> APIResponse:
        """Handle incoming request"""
        handler = self.handlers.get(self.method)
        if not handler:
            return APIResponse("error", error=f"No handler for {self.method}")
        try:
            result = await handler(data) if asyncio.iscoroutinefunction(handler) else handler(data)
            return APIResponse("success", data=result)
        except Exception as e:
            return APIResponse("error", error=str(e))


# Backend API Endpoints
class UserAPI(APIEndpoint):
    """User management endpoints"""
    def __init__(self):
        super().__init__("/api/users", "GET")
        self.users = {}
    
    async def get_users(self, data: Dict = None) -> Dict:
        """Get all users"""
        return {"users": list(self.users.values())}
    
    async def create_user(self, data: Dict) -> Dict:
        """Create new user"""
        user_id = str(len(self.users) + 1)
        self.users[user_id] = {
            "id": user_id,
            "name": data.get("name"),
            "email": data.get("email"),
            "created_at": datetime.now().isoformat(),
        }
        return {"user": self.users[user_id]}


class DataAPI(APIEndpoint):
    """Data management endpoints"""
    def __init__(self):
        super().__init__("/api/data", "GET")
        self.data_store = []
    
    async def get_data(self, filters: Dict = None) -> Dict:
        """Retrieve data with optional filters"""
        if not filters:
            return {"data": self.data_store}
        
        filtered = [d for d in self.data_store if self._match_filters(d, filters)]
        return {"data": filtered}
    
    async def add_data(self, data: Dict) -> Dict:
        """Add new data item"""
        item = {
            "id": len(self.data_store) + 1,
            "data": data,
            "created_at": datetime.now().isoformat(),
        }
        self.data_store.append(item)
        return {"item": item}
    
    def _match_filters(self, item: Dict, filters: Dict) -> bool:
        """Check if item matches filters"""
        for key, value in filters.items():
            if item.get(key) != value:
                return False
        return True
'''
        return code

    def _generate_database_models(self, description: str) -> str:
        """Generate database model definitions"""
        code = '''"""
Database Models - ORM-style model definitions
"""

from typing import Dict, List, Optional, Any
from datetime import datetime
from dataclasses import dataclass, asdict, field


@dataclass
class BaseModel:
    """Base model with common fields"""
    id: str = field(default_factory=lambda: str(datetime.now().timestamp()))
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    
    def to_dict(self) -> Dict:
        """Convert model to dictionary"""
        return asdict(self)
    
    def update(self, **kwargs):
        """Update model fields"""
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)
        self.updated_at = datetime.now().isoformat()


@dataclass
class User(BaseModel):
    """User model"""
    name: str = ""
    email: str = ""
    is_active: bool = True
    role: str = "user"
    metadata: Dict = field(default_factory=dict)


@dataclass
class Task(BaseModel):
    """Task model"""
    title: str = ""
    description: str = ""
    status: str = "pending"  # pending, in_progress, completed
    priority: int = 1  # 1=low, 5=high
    assigned_to: str = ""
    due_date: Optional[str] = None
    tags: List[str] = field(default_factory=list)


@dataclass
class Entity(BaseModel):
    """Generic entity model"""
    entity_type: str = ""
    name: str = ""
    attributes: Dict = field(default_factory=dict)
    relationships: List[str] = field(default_factory=list)


class DatabaseManager:
    """Simple in-memory database manager"""
    def __init__(self):
        self.users: Dict[str, User] = {}
        self.tasks: Dict[str, Task] = {}
        self.entities: Dict[str, Entity] = {}
    
    def create_user(self, **kwargs) -> User:
        """Create and store user"""
        user = User(**kwargs)
        self.users[user.id] = user
        return user
    
    def get_user(self, user_id: str) -> Optional[User]:
        """Retrieve user by ID"""
        return self.users.get(user_id)
    
    def create_task(self, **kwargs) -> Task:
        """Create and store task"""
        task = Task(**kwargs)
        self.tasks[task.id] = task
        return task
    
    def get_task(self, task_id: str) -> Optional[Task]:
        """Retrieve task by ID"""
        return self.tasks.get(task_id)
    
    def delete_task(self, task_id: str) -> bool:
        """Delete task"""
        if task_id in self.tasks:
            del self.tasks[task_id]
            return True
        return False
'''
        return code

    def _generate_business_logic(self, description: str) -> str:
        """Generate business logic and algorithms"""
        code = '''"""
Business Logic - Core algorithms and processing
"""

from typing import Dict, List, Optional, Callable, Any
from datetime import datetime, timedelta
import json


class BusinessLogic:
    """Core business logic dispatcher"""
    
    @staticmethod
    def validate_input(data: Dict, required_fields: List[str]) -> tuple[bool, Optional[str]]:
        """
        Validate input data.
        
        Args:
            data: Input data to validate
            required_fields: List of required field names
        
        Returns:
            Tuple of (is_valid, error_message)
        """
        if not data:
            return False, "Input data is empty"
        
        missing_fields = [field for field in required_fields if field not in data]
        if missing_fields:
            return False, f"Missing required fields: {', '.join(missing_fields)}"
        
        return True, None
    
    @staticmethod
    def process_data(data: Dict, pipeline: List[Callable]) -> Dict:
        """
        Process data through processing pipeline.
        
        Args:
            data: Input data
            pipeline: List of processing functions
        
        Returns:
            Processed data
        """
        result = data.copy()
        for processor in pipeline:
            try:
                result = processor(result)
            except Exception as e:
                result["processing_error"] = str(e)
                break
        return result
    
    @staticmethod
    def aggregate_results(results: List[Dict], aggregation_method: str = "merge") -> Dict:
        """
        Aggregate multiple results.
        
        Args:
            results: List of result dictionaries
            aggregation_method: "merge", "combine", or "chain"
        
        Returns:
            Aggregated result
        """
        if not results:
            return {"aggregated": None, "count": 0}
        
        if aggregation_method == "merge":
            merged = {}
            for result in results:
                merged.update(result)
            return {"aggregated": merged, "count": len(results)}
        
        elif aggregation_method == "combine":
            return {"aggregated": results, "count": len(results)}
        
        elif aggregation_method == "chain":
            current = results[0] if results else {}
            for result in results[1:]:
                current = {**current, **result}
            return {"aggregated": current, "count": len(results)}
        
        return {"aggregated": None, "count": 0}


class CacheManager:
    """Simple caching logic"""
    def __init__(self, ttl_seconds: int = 3600):
        self.cache: Dict[str, tuple] = {}
        self.ttl = ttl_seconds
    
    def get(self, key: str) -> Optional[Any]:
        """Get cached value"""
        if key not in self.cache:
            return None
        value, expiry = self.cache[key]
        if datetime.now() > expiry:
            del self.cache[key]
            return None
        return value
    
    def set(self, key: str, value: Any):
        """Set cached value"""
        self.cache[key] = (value, datetime.now() + timedelta(seconds=self.ttl))
    
    def clear(self):
        """Clear all cache"""
        self.cache.clear()
'''
        return code

    def _generate_error_handling(self) -> str:
        """Generate error handling and logging"""
        code = '''"""
Error Handling and Logging
"""

import traceback
from typing import Optional, Callable, Any
from datetime import datetime
import json


class APIError(Exception):
    """Custom exception for API errors"""
    def __init__(self, message: str, code: str = "INTERNAL_ERROR", status_code: int = 500):
        self.message = message
        self.code = code
        self.status_code = status_code
        super().__init__(self.message)


class ValidationError(APIError):
    """Validation error exception"""
    def __init__(self, message: str):
        super().__init__(message, code="VALIDATION_ERROR", status_code=400)


class NotFoundError(APIError):
    """Resource not found exception"""
    def __init__(self, resource: str):
        super().__init__(f"{resource} not found", code="NOT_FOUND", status_code=404)


class Logger:
    """Simple logging utility"""
    def __init__(self, name: str = "backend"):
        self.name = name
        self.logs = []
    
    def log(self, level: str, message: str, data: Any = None):
        """Log a message"""
        entry = {
            "timestamp": datetime.now().isoformat(),
            "level": level,
            "message": message,
            "data": data,
        }
        self.logs.append(entry)
        print(f"[{level}] {message}", f"| {data}" if data else "")
    
    def info(self, message: str, data: Any = None):
        """Log info"""
        self.log("INFO", message, data)
    
    def error(self, message: str, data: Any = None):
        """Log error"""
        self.log("ERROR", message, data)
    
    def debug(self, message: str, data: Any = None):
        """Log debug"""
        self.log("DEBUG", message, data)
    
    def get_logs(self, level: Optional[str] = None) -> list:
        """Get logs, optionally filtered by level"""
        if level:
            return [l for l in self.logs if l["level"] == level]
        return self.logs


def safe_execute(func: Callable, *args, **kwargs) -> tuple[Any, Optional[str]]:
    """
    Safely execute a function with error handling.
    
    Returns:
        Tuple of (result, error_message)
    """
    try:
        result = func(*args, **kwargs)
        return result, None
    except Exception as e:
        error_msg = f"{type(e).__name__}: {str(e)}"
        traceback.print_exc()
        return None, error_msg
'''
        return code

    def _generate_documentation(self, description: str) -> str:
        """Generate backend documentation"""
        return f"""
## Backend Component Documentation

### Overview
This backend component provides:
- RESTful API endpoints for data management
- Database models and ORM-style abstractions
- Business logic and processing pipelines
- Error handling and logging utilities

### Original Task
{description}

### Key Classes
- `APIResponse`: Standard response wrapper
- `APIEndpoint`: Base endpoint class
- `UserAPI`: User management endpoints
- `DataAPI`: Data management endpoints
- `DatabaseManager`: In-memory database
- `BusinessLogic`: Core business logic
- `Logger`: Logging utility

### Usage
1. Create database manager instance
2. Register API endpoints
3. Process requests through business logic
4. Return standardized responses
"""

    def _identify_dependencies(self, description: str) -> list:
        """Identify backend dependencies"""
        deps = [
            "typing",
            "datetime",
            "json",
            "enum",
            "dataclasses",
            "asyncio",
            "traceback",
        ]
        
        # Add conditional dependencies based on description
        if "database" in description.lower():
            deps.append("sqlalchemy")
        if "cache" in description.lower():
            deps.append("redis")
        if "async" in description.lower() or "concurrent" in description.lower():
            deps.append("aiofiles")
        
        return deps
