"""
Frontend Agent - Specialized in UI, user interaction, and data visualization
"""

from typing import Dict, Optional
from datetime import datetime


class FrontendAgent:
    """
    Specialized agent for frontend development tasks.
    Generates UI components, user interactions, and data visualizations.
    """

    def __init__(self, orchestrator=None):
        """
        Initialize Frontend Agent.
        
        Args:
            orchestrator: Reference to TaskOrchestrator
        """
        self.orchestrator = orchestrator
        self.name = "Frontend Agent"
        self.role = "Frontend Developer"
        self.specialties = ["UI Design", "User Interaction", "Data Visualization"]

    def generate_code(self, subtask: Dict) -> Dict:
        """
        Generate frontend code from a subtask.
        
        Args:
            subtask: Frontend subtask from decomposer
                {
                    "type": "frontend",
                    "description": "...",
                    "task_id": "...",
                    ...
                }
        
        Returns:
            Dictionary with generated code and metadata
        """
        subtask_desc = subtask.get("description", "")
        task_id = subtask.get("task_id", "")
        
        # Generate frontend code structure
        code = self._generate_streamlit_app(subtask_desc)
        code += "\n\n"
        code += self._generate_ui_components(subtask_desc)
        code += "\n\n"
        code += self._generate_state_management()
        code += "\n\n"
        code += self._generate_event_handlers(subtask_desc)
        
        return {
            "code": code,
            "language": "python",
            "agent": self.name,
            "subtask_id": task_id,
            "generated_at": datetime.now().isoformat(),
            "documentation": self._generate_documentation(subtask_desc),
            "dependencies": self._identify_dependencies(subtask_desc),
        }

    def _generate_streamlit_app(self, description: str) -> str:
        """Generate Streamlit app structure"""
        code = '''"""
Frontend Application - Auto-generated by Frontend Agent
Streamlit-based user interface with components and interactions
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from typing import Dict, List, Optional, Callable
from datetime import datetime
from dataclasses import dataclass


# Page configuration
st.set_page_config(
    page_title="Frontend Application",
    page_icon="🎯",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS styling
st.markdown(
    """
    <style>
    .main-header {
        font-size: 2.5em;
        font-weight: bold;
        color: #FF6B35;
        margin-bottom: 10px;
    }
    .section-header {
        font-size: 1.5em;
        font-weight: bold;
        color: #1E3A8A;
        margin-top: 20px;
        border-bottom: 2px solid #FF6B35;
        padding-bottom: 10px;
    }
    .status-badge {
        display: inline-block;
        padding: 5px 10px;
        border-radius: 5px;
        font-weight: bold;
    }
    .status-success {
        background-color: #10b981;
        color: white;
    }
    .status-warning {
        background-color: #f59e0b;
        color: white;
    }
    .status-error {
        background-color: #ef4444;
        color: white;
    }
    </style>
    """,
    unsafe_allow_html=True,
)


class StreamlitApp:
    """Main Streamlit application class"""
    
    def __init__(self):
        self.initialize_session_state()
    
    def initialize_session_state(self):
        """Initialize Streamlit session state"""
        if "page" not in st.session_state:
            st.session_state.page = "home"
        if "user_data" not in st.session_state:
            st.session_state.user_data = {}
        if "notifications" not in st.session_state:
            st.session_state.notifications = []
    
    def render_header(self):
        """Render application header"""
        col1, col2 = st.columns([4, 1])
        with col1:
            st.markdown('<div class="main-header">🎯 Frontend Application</div>', unsafe_allow_html=True)
        with col2:
            if st.button("🔄 Refresh"):
                st.rerun()
    
    def render_sidebar(self):
        """Render sidebar navigation"""
        with st.sidebar:
            st.markdown("### 📊 Navigation")
            
            page = st.radio(
                "Go to page:",
                ["Home", "Dashboard", "Data", "Settings"],
                label_visibility="collapsed"
            )
            st.session_state.page = page.lower()
            
            st.markdown("---")
            st.markdown("### ℹ️ Info")
            st.write(f"Current Page: **{st.session_state.page}**")
            st.write(f"Last Updated: **{datetime.now().strftime('%H:%M:%S')}**")
    
    def render_notifications(self):
        """Render notification area"""
        if st.session_state.notifications:
            for notif in st.session_state.notifications:
                if notif["type"] == "success":
                    st.success(notif["message"])
                elif notif["type"] == "error":
                    st.error(notif["message"])
                elif notif["type"] == "warning":
                    st.warning(notif["message"])
                else:
                    st.info(notif["message"])
            st.session_state.notifications = []
    
    def run(self):
        """Main application entry point"""
        self.render_header()
        self.render_sidebar()
        self.render_notifications()
        
        # Route based on selected page
        if st.session_state.page == "home":
            self.page_home()
        elif st.session_state.page == "dashboard":
            self.page_dashboard()
        elif st.session_state.page == "data":
            self.page_data()
        elif st.session_state.page == "settings":
            self.page_settings()
    
    def page_home(self):
        """Home page"""
        st.markdown('<div class="section-header">🏠 Home</div>', unsafe_allow_html=True)
        
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Total Items", 42)
        with col2:
            st.metric("Active Users", 15)
        with col3:
            st.metric("System Health", "✓ Healthy")
        
        st.markdown("---")
        st.write("Welcome to the frontend application!")
        st.info("Select a page from the sidebar to get started.")
    
    def page_dashboard(self):
        """Dashboard page with visualizations"""
        st.markdown('<div class="section-header">📊 Dashboard</div>', unsafe_allow_html=True)
        
        # Sample data visualization
        data = {
            "Date": pd.date_range("2024-01-01", periods=30),
            "Value": range(30),
            "Category": ["A" if i % 2 == 0 else "B" for i in range(30)],
        }
        df = pd.DataFrame(data)
        
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("#### Time Series")
            fig = px.line(df, x="Date", y="Value", title="Value Over Time")
            st.plotly_chart(fig, use_container_width=True)
        
        with col2:
            st.markdown("#### Distribution by Category")
            fig = px.bar(df, x="Category", y="Value", title="Values by Category")
            st.plotly_chart(fig, use_container_width=True)
    
    def page_data(self):
        """Data management page"""
        st.markdown('<div class="section-header">📋 Data</div>', unsafe_allow_html=True)
        
        col1, col2 = st.columns([3, 1])
        
        with col1:
            st.markdown("#### Data Input")
            with st.form("data_input"):
                name = st.text_input("Name")
                value = st.number_input("Value", min_value=0)
                submit = st.form_submit_button("Add Data")
                
                if submit and name:
                    st.session_state.notifications.append({
                        "type": "success",
                        "message": f"Added {name} with value {value}"
                    })
                    st.session_state.user_data[name] = value
        
        with col2:
            st.markdown("#### Actions")
            if st.button("Clear All"):
                st.session_state.user_data = {}
                st.session_state.notifications.append({
                    "type": "warning",
                    "message": "Data cleared"
                })
        
        # Display stored data
        if st.session_state.user_data:
            st.markdown("#### Stored Data")
            df = pd.DataFrame(list(st.session_state.user_data.items()), columns=["Name", "Value"])
            st.dataframe(df, use_container_width=True)
    
    def page_settings(self):
        """Settings page"""
        st.markdown('<div class="section-header">⚙️ Settings</div>', unsafe_allow_html=True)
        
        st.markdown("#### Application Settings")
        
        theme = st.radio("Theme", ["Light", "Dark"])
        notifications = st.checkbox("Enable Notifications", value=True)
        auto_refresh = st.checkbox("Auto Refresh", value=False)
        
        if auto_refresh:
            refresh_interval = st.slider("Refresh Interval (seconds)", 1, 60, 30)
        
        if st.button("Save Settings"):
            st.session_state.notifications.append({
                "type": "success",
                "message": "Settings saved"
            })


# Application entry point
if __name__ == "__main__":
    app = StreamlitApp()
    app.run()
'''
        return code

    def _generate_ui_components(self, description: str) -> str:
        """Generate reusable UI components"""
        code = '''"""
Reusable UI Components
"""

import streamlit as st
from typing import Optional, Callable, List, Dict, Any
from dataclasses import dataclass


class UIComponent:
    """Base class for UI components"""
    def __init__(self, title: str, key: str = None):
        self.title = title
        self.key = key
    
    def render(self):
        """Render component - override in subclasses"""
        raise NotImplementedError


class Card(UIComponent):
    """Reusable card component"""
    def __init__(self, title: str, content: str, icon: str = "📌"):
        super().__init__(title)
        self.content = content
        self.icon = icon
    
    def render(self):
        """Render card"""
        with st.container():
            st.markdown(f"### {self.icon} {self.title}")
            st.write(self.content)
            st.divider()


class MetricCard(UIComponent):
    """Metric display card"""
    def __init__(self, label: str, value: str, delta: str = None, icon: str = "📊"):
        super().__init__(label)
        self.value = value
        self.delta = delta
        self.icon = icon
    
    def render(self):
        """Render metric card"""
        st.metric(label=f"{self.icon} {self.title}", value=self.value, delta=self.delta)


class FormBuilder:
    """Builder for forms with validation"""
    def __init__(self, form_id: str):
        self.form_id = form_id
        self.fields = {}
    
    def add_text_input(self, field_name: str, label: str, required: bool = False) -> "FormBuilder":
        """Add text input field"""
        self.fields[field_name] = {
            "type": "text",
            "label": label,
            "required": required,
        }
        return self
    
    def add_number_input(self, field_name: str, label: str, min_val: int = 0, max_val: int = 100) -> "FormBuilder":
        """Add number input field"""
        self.fields[field_name] = {
            "type": "number",
            "label": label,
            "min": min_val,
            "max": max_val,
        }
        return self
    
    def add_select(self, field_name: str, label: str, options: List[str]) -> "FormBuilder":
        """Add select dropdown"""
        self.fields[field_name] = {
            "type": "select",
            "label": label,
            "options": options,
        }
        return self
    
    def render(self, on_submit: Optional[Callable] = None) -> Dict[str, Any]:
        """Render form and return values"""
        with st.form(self.form_id):
            values = {}
            
            for field_name, field_config in self.fields.items():
                field_type = field_config["type"]
                label = field_config["label"]
                
                if field_type == "text":
                    values[field_name] = st.text_input(label)
                elif field_type == "number":
                    values[field_name] = st.number_input(label, 
                                                         min_value=field_config.get("min", 0),
                                                         max_value=field_config.get("max", 100))
                elif field_type == "select":
                    values[field_name] = st.selectbox(label, field_config["options"])
            
            if st.form_submit_button("Submit"):
                if on_submit:
                    return on_submit(values)
                return values
        
        return {}


class DataTable:
    """Data display table with sorting and filtering"""
    def __init__(self, data: List[Dict], title: str = "Data Table"):
        self.data = data
        self.title = title
    
    def render(self):
        """Render data table"""
        st.markdown(f"### {self.title}")
        
        if not self.data:
            st.info("No data to display")
            return
        
        # Convert to DataFrame
        df = pd.DataFrame(self.data)
        
        # Filtering options
        st.markdown("#### Filters")
        col1, col2 = st.columns(2)
        
        with col1:
            if "id" in df.columns:
                selected_ids = st.multiselect("Filter by ID", df["id"].unique())
                if selected_ids:
                    df = df[df["id"].isin(selected_ids)]
        
        # Display table
        st.dataframe(df, use_container_width=True)
'''
        return code

    def _generate_state_management(self) -> str:
        """Generate state management utilities"""
        code = '''"""
State Management - Utility functions for Streamlit state
"""

import streamlit as st
from typing import Any, Optional, Callable, Dict, List


class StateManager:
    """Manages Streamlit session state"""
    
    @staticmethod
    def set(key: str, value: Any):
        """Set session state value"""
        st.session_state[key] = value
    
    @staticmethod
    def get(key: str, default: Any = None) -> Any:
        """Get session state value"""
        return st.session_state.get(key, default)
    
    @staticmethod
    def exists(key: str) -> bool:
        """Check if key exists in state"""
        return key in st.session_state
    
    @staticmethod
    def delete(key: str):
        """Delete key from state"""
        if key in st.session_state:
            del st.session_state[key]
    
    @staticmethod
    def clear():
        """Clear all state"""
        st.session_state.clear()
    
    @staticmethod
    def get_all() -> Dict:
        """Get all state"""
        return dict(st.session_state)


class PageState:
    """Manages page-specific state"""
    def __init__(self, page_name: str):
        self.page_name = page_name
        self.state_key = f"page_{page_name}"
    
    def set_data(self, data: Dict):
        """Set page data"""
        StateManager.set(self.state_key, data)
    
    def get_data(self) -> Dict:
        """Get page data"""
        return StateManager.get(self.state_key, {})
    
    def update_data(self, updates: Dict):
        """Update page data"""
        current = self.get_data()
        current.update(updates)
        self.set_data(current)


class EventBus:
    """Simple event management system"""
    def __init__(self):
        self.subscribers = {}
    
    def subscribe(self, event_name: str, callback: Callable):
        """Subscribe to event"""
        if event_name not in self.subscribers:
            self.subscribers[event_name] = []
        self.subscribers[event_name].append(callback)
    
    def publish(self, event_name: str, data: Any = None):
        """Publish event to subscribers"""
        if event_name in self.subscribers:
            for callback in self.subscribers[event_name]:
                callback(data)
    
    def unsubscribe(self, event_name: str, callback: Callable):
        """Unsubscribe from event"""
        if event_name in self.subscribers:
            self.subscribers[event_name].remove(callback)
'''
        return code

    def _generate_event_handlers(self, description: str) -> str:
        """Generate event handling logic"""
        code = '''"""
Event Handlers - User interaction handlers
"""

from typing import Callable, Dict, Any, Optional
from datetime import datetime


class EventHandler:
    """Base event handler"""
    def __init__(self, event_name: str):
        self.event_name = event_name
        self.callbacks = []
    
    def register(self, callback: Callable) -> "EventHandler":
        """Register callback for event"""
        self.callbacks.append(callback)
        return self
    
    def trigger(self, data: Any = None) -> List[Any]:
        """Trigger all registered callbacks"""
        results = []
        for callback in self.callbacks:
            try:
                result = callback(data)
                results.append(result)
            except Exception as e:
                print(f"Error in {self.event_name}: {str(e)}")
        return results


class UserInteractionHandler:
    """Handles user interactions"""
    
    def __init__(self):
        self.click_handlers = {}
        self.submit_handlers = {}
        self.change_handlers = {}
        self.interaction_log = []
    
    def on_button_click(self, button_id: str, callback: Callable):
        """Register button click handler"""
        if button_id not in self.click_handlers:
            self.click_handlers[button_id] = []
        self.click_handlers[button_id].append(callback)
    
    def on_form_submit(self, form_id: str, callback: Callable):
        """Register form submit handler"""
        if form_id not in self.submit_handlers:
            self.submit_handlers[form_id] = []
        self.submit_handlers[form_id].append(callback)
    
    def on_value_change(self, field_id: str, callback: Callable):
        """Register value change handler"""
        if field_id not in self.change_handlers:
            self.change_handlers[field_id] = []
        self.change_handlers[field_id].append(callback)
    
    def trigger_click(self, button_id: str, data: Any = None):
        """Trigger button click"""
        self._log_interaction("click", button_id, data)
        if button_id in self.click_handlers:
            for callback in self.click_handlers[button_id]:
                callback(data)
    
    def trigger_submit(self, form_id: str, data: Any = None):
        """Trigger form submit"""
        self._log_interaction("submit", form_id, data)
        if form_id in self.submit_handlers:
            for callback in self.submit_handlers[form_id]:
                callback(data)
    
    def trigger_change(self, field_id: str, data: Any = None):
        """Trigger value change"""
        self._log_interaction("change", field_id, data)
        if field_id in self.change_handlers:
            for callback in self.change_handlers[field_id]:
                callback(data)
    
    def _log_interaction(self, interaction_type: str, id: str, data: Any):
        """Log user interaction"""
        self.interaction_log.append({
            "type": interaction_type,
            "id": id,
            "timestamp": datetime.now().isoformat(),
            "data": data,
        })
    
    def get_interaction_log(self, limit: int = 100) -> list:
        """Get recent interactions"""
        return self.interaction_log[-limit:]
'''
        return code

    def _generate_documentation(self, description: str) -> str:
        """Generate frontend documentation"""
        return f"""
## Frontend Component Documentation

### Overview
This frontend component provides:
- Streamlit-based web interface
- Reusable UI components (cards, forms, tables)
- State management utilities
- Event handling system
- Data visualization with Plotly

### Original Task
{description}

### Key Classes
- `StreamlitApp`: Main application class
- `UIComponent`: Base component class
- `Card`: Reusable card component
- `FormBuilder`: Form builder with validation
- `DataTable`: Interactive data table
- `StateManager`: Session state management
- `EventBus`: Event system
- `UserInteractionHandler`: Interaction handling

### Pages
- Home: Overview and metrics
- Dashboard: Data visualizations
- Data: Data management and input
- Settings: Application settings

### Usage
1. Create StreamlitApp instance
2. Initialize session state
3. Render components based on page
4. Handle user interactions
"""

    def _identify_dependencies(self, description: str) -> list:
        """Identify frontend dependencies"""
        deps = [
            "streamlit",
            "pandas",
            "plotly",
            "typing",
            "datetime",
            "dataclasses",
        ]
        
        # Add conditional dependencies
        if "chart" in description.lower() or "visualization" in description.lower():
            deps.append("matplotlib")
        if "table" in description.lower() or "data" in description.lower():
            deps.append("altair")
        
        return deps
